# Generated by Django 5.0.6 on 2024-05-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_aboutinfo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isStaff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=100, null=True)),
                ('Phone', models.CharField(max_length=10)),
                ('Gender', models.BooleanField(null=True)),
                ('HouseNumber', models.CharField(max_length=255, null=True)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.account')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('DistrictID', models.IntegerField(primary_key=True, serialize=False)),
                ('DistrictName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('FoodID', models.AutoField(primary_key=True, serialize=False)),
                ('FoodName', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('originPrice', models.FloatField()),
                ('ImageFood', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('IsDeleted', models.BooleanField()),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityIG', models.FloatField()),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.food')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('IngredientsId', models.IntegerField(primary_key=True, serialize=False)),
                ('IngredientsName', models.CharField(max_length=200)),
                ('IngredientsPrice', models.FloatField()),
                ('IngredientsQty', models.FloatField()),
                ('IsDeleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('MeasureID', models.IntegerField(primary_key=True, serialize=False)),
                ('MeasureName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityOF', models.IntegerField()),
                ('PriceOF', models.FloatField()),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.food')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField()),
                ('arrive_time', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('temp_money', models.FloatField()),
                ('shipping_money', models.FloatField()),
                ('total_money', models.FloatField()),
                ('status_odr', models.IntegerField()),
                ('house_number', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.IntegerField(primary_key=True, serialize=False)),
                ('Star', models.IntegerField()),
                ('Content', models.TextField()),
                ('Img', models.TextField()),
                ('DateReview', models.DateTimeField()),
                ('CustomerID', models.IntegerField()),
                ('FoodID', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.customer')),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.food')),
                ('Orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.IntegerField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffID', models.IntegerField(primary_key=True, serialize=False)),
                ('StaffName', models.CharField(max_length=100, null=True)),
                ('Phone', models.CharField(max_length=10, null=True)),
                ('Gender', models.BooleanField(null=True)),
                ('HouseNumber', models.CharField(max_length=255, null=True)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.account')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.role')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('WardId', models.IntegerField(primary_key=True, serialize=False)),
                ('WardName', models.CharField(max_length=50)),
                ('DistrictID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='Home.district')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutInfo',
        ),
        migrations.DeleteModel(
            name='ClientReview',
        ),
        migrations.RemoveField(
            model_name='comingsoon',
            name='category',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='RestaurantInfo',
        ),
        migrations.AddField(
            model_name='cart',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.food'),
        ),
        migrations.AddField(
            model_name='food_ingredients',
            name='Ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.ingredients'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='Measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.measure'),
        ),
        migrations.AddField(
            model_name='order_food',
            name='Orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.orders'),
        ),
        migrations.AddField(
            model_name='orders',
            name='chef_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chef_orders', to='Home.staff'),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipper_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipper_orders', to='Home.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='Ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.ward'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.ward'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.ward'),
        ),
        migrations.DeleteModel(
            name='ComingSoon',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
