# Generated by Django 5.0.6 on 2024-05-10 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_account_cart_category_customer_district_food_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='arrive_time',
            new_name='Arrive_time',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='chef_staff',
            new_name='Chef_staff',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='customer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='customer_name',
            new_name='Customer_name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='house_number',
            new_name='House_number',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='note',
            new_name='Note',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_id',
            new_name='Order_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='phone_number',
            new_name='Phone_number',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='sale_date',
            new_name='Sale_date',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='shipper_staff',
            new_name='Shipper_staff',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='shipping_money',
            new_name='Shipping_money',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='status_odr',
            new_name='Status_odr',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='temp_money',
            new_name='Temp_money',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='total_money',
            new_name='Total_money',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='ward',
            new_name='Ward',
        ),
    ]
