# Generated by Django 5.0.6 on 2024-05-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_rename_arrive_time_orders_arrive_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Arrive_time',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Chef_staff',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Sale_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Shipper_staff',
        ),
    ]
